name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        toolchain:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
        include:
        - toolchain: x86_64-unknown-linux-gnu
          builder: ubuntu-latest
          os: linux
        - toolchain: x86_64-apple-darwin
          builder: macos-latest
          os: macos
        - toolchain: x86_64-pc-windows-msvc
          builder: windows-latest
          os: windows

    name: build - ${{ matrix.toolchain }}
    runs-on: ${{ matrix.builder }}

    steps:
      - name: Ls
        run: ls ..

      - name: Build
        run: cargo build
