name: win-aarch64

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Toolchain versions
      run: |
        rustc --version
        cargo --version

    - name: Add aarch64-pc-windows-msvc target
      run: rustup target add aarch64-pc-windows-msvc

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo install extract-audio --target aarch64-pc-windows-msvc --git https://github.com/egorsmkv/extract-audio

    - name: Upload artifact
      uses: actions/upload-artifact@v5
      with:
        name: extract-audio_aarch64_msvc_windows.exe
        path: C:\Users\runneradmin\.cargo\bin\extract-audio.exe
